version: "3"

volumes:
  mongodata:

networks: 
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  apiso:
    build: ./apiSo
    env_file:
      - .env
    ports:
      - "$APISO_PORT:80"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/apiSo
    networks:
      - backend

  apifrt:
    build: ./apiFrt
    env_file:
      - .env
    ports:
      - "$APIFRT_PORT:81"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/apiFrt
    networks:
      - backend
      - frontend

  apidb:
    build: ./apiDB
    env_file:
      - .env
    ports:
      - "$APIDB_PORT:82"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/apiDB
    networks:
      - backend

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "$FRT_PORT:83"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/frontend
    networks:
      - frontend

  mongo:
    image: mongo
    ports:
      - "$MNG_PORT:27017"
    volumes:
      - mongodata:/data/db
