version: "3"

volumes:
  mongodata:

networks: 
  frontend:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0/24"

  backend:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.0.0/24"


services:

  apiso:
    build: ./apiSo
    env_file:
      - .env
    ports:
      - "$ASO_PORT:80"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/apiSo
    networks:
      backend:
        ipv4_address: "192.168.0.2"
    environment:
    - NAME=apiso

  apifrt:
    build: ./apiFrt
    env_file:
      - .env
    ports:
      - "$AFRT_PORT:81"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/apiFrt
    networks:
      backend:
        ipv4_address: "192.168.0.3"
      frontend:
        ipv4_address: "192.168.1.2"
    environment:
    - NAME=apifrt

  apidb:
    build: ./apiDB
    env_file:
      - .env
    ports:
      - "$ADB_PORT:82"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/apiDB
    networks:
      backend:
        ipv4_address: "192.168.0.4"
    environment:
    - NAME=apidb

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "$FRT_PORT:83"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/frontend
    networks:
      frontend:
        ipv4_address: "192.168.1.3"
    environment:
    - NAME=frontend

  redis:
    image: redis:alpine
    env_file:
      - .env
    command: redis-server
    ports:
      - "$RDS_PORT:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      backend:
        ipv4_address: "192.168.0.6"

  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "$MNG_PORT:27017"
    volumes:
      - mongodata:/data/db
    logging:
      driver: $MNG_LOGS
    networks:
      backend:
        ipv4_address: "192.168.0.5"