version: "2"
services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/backend
  frontend:
    build: ./frontend
    ports:
      - "81:81"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/frontend
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
