version: "2"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${BKT_PORT}:80"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/backend
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "${FRT_PORT}:81"
    depends_on:
      - mongo
    volumes:
      - .:/opt/app/frontend
  mongo:
    image: mongo
    ports:
      - "${MNG_PORT}:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
